version: "3"

services:
  sonarqube:
    container_name: sonarqube-container # Custom container name
    image: sonarqube:lts-community
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - bridge
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  db:
    image: mysql:5.7
    networks:
      - bridge
    ports:
      - "3307:3306" 
    environment:
      - MYSQL_DATABASE=sonar
      - MYSQL_ROOT_PASSWORD=sonar
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=sonar
    volumes:
      - sonar_db:/var/lib/mysql
      - sonar_conf:/etc/mysql/conf.d

networks:
  bridge:
    driver: bridge

volumes:
   sonarqube_conf:
   sonarqube_data:
   sonarqube_extensions:
   sonarqube_logs:
   sonarqube_temp:
   sonar_db:
   sonar_conf: